### ISSUE TITLE
Phase 4.2: Extend API and WebSocket for Multi-Provider Support

### ISSUE THREAD

**Issue by arjaygg** [arjaygg/supervisor-coding-agent#50]
## User Story
**As a** frontend developer  
**I want** API endpoints and WebSocket feeds that support multi-provider functionality  
**So that** users can monitor and control provider selection and performance

## Description
Extend the existing FastAPI endpoints and WebSocket connections to support multi-provider functionality, enabling frontend integration and real-time monitoring.

## Acceptance Criteria
- [ ] Provider status and health API endpoints
- [ ] Real-time provider metrics via WebSocket
- [ ] Task routing preferences API
- [ ] Provider configuration management endpoints
- [ ] Provider usage analytics endpoints
- [ ] Integration with existing API structure
- [ ] OpenAPI documentation updated
- [ ] WebSocket events for provider status changes

## Technical Requirements
- Extend `supervisor_agent/api/routes/` with provider endpoints
- Update WebSocket handlers in `supervisor_agent/api/websocket.py`
- Add provider-related schemas in `supervisor_agent/db/schemas.py`
- Integrate with existing authentication and authorization
- Add API versioning for new endpoints

## API Endpoints to Add
```yaml
/api/v1/providers:
  get: List all configured providers
  post: Register new provider

/api/v1/providers/{id}:
  get: Get provider details and status
  put: Update provider configuration
  delete: Remove provider

/api/v1/providers/{id}/health:
  get: Get detailed provider health metrics

/api/v1/providers/usage:
  get: Get usage analytics across providers

/api/v1/tasks/{id}/provider:
  get: Get provider assignment for task
  put: Change provider preference for task
```

## Definition of Done
- [ ] All API endpoints implemented and tested
- [ ] WebSocket integration working
- [ ] OpenAPI docs automatically generated
- [ ] Frontend integration ready
- [ ] Performance impact minimal (<10ms per request)
- [ ] Comprehensive API tests added

## Dependencies
- Requires: Phase 3 Provider Coordination
- Enables: Frontend integration and monitoring
- Integrates with: Existing API infrastructure

## Effort Estimation
- **Story Points**: 30
- **Estimated Time**: 2 days
- **Priority**: Medium

## Labels
- Phase: 4
- Type: API
- Priority: Medium
- Component: Backend, Frontend
